"""db_money

Revision ID: 3463057ac0c1
Revises: 1c12007e268c
Create Date: 2023-05-30 00:39:10.203515

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3463057ac0c1"
down_revision = "1c12007e268c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("cost_unit", sa.Float(), nullable=False),
        sa.Column("investment_account_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["investment_account_id"], ["investment_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_assets_id"), "assets", ["id"], unique=False)
    op.create_table(
        "broker_report",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_start", sa.Date(), nullable=False),
        sa.Column("date_end", sa.Date(), nullable=False),
        sa.Column("file", sa.String(), nullable=False),
        sa.Column("investment_account_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["investment_account_id"], ["investment_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_broker_report_id"), "broker_report", ["id"], unique=False)
    op.create_table(
        "operation_securities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("operation_type", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("cost_unit", sa.Float(), nullable=False),
        sa.Column("nkd", sa.Float(), nullable=False),
        sa.Column("commission_broker", sa.Float(), nullable=False),
        sa.Column("commission_rialto", sa.Float(), nullable=False),
        sa.Column("broker_report_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["broker_report_id"], ["broker_report.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_operation_securities_id"), "operation_securities", ["id"], unique=False)
    op.add_column("investment_account", sa.Column("broker_name", sa.String(), nullable=True))
    op.add_column("operations", sa.Column("code", sa.String(), nullable=False))
    op.add_column("operations", sa.Column("broker_report_id", sa.Integer(), nullable=False))
    op.alter_column("operations", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_constraint("operations_name_key", "operations", type_="unique")
    op.drop_constraint("operations_investment_account_id_fkey", "operations", type_="foreignkey")
    op.create_foreign_key(None, "operations", "broker_report", ["broker_report_id"], ["id"], ondelete="CASCADE")
    op.drop_column("operations", "investment_account_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operations", sa.Column("investment_account_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "operations", type_="foreignkey")
    op.create_foreign_key(
        "operations_investment_account_id_fkey",
        "operations",
        "investment_account",
        ["investment_account_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint("operations_name_key", "operations", ["name"])
    op.alter_column("operations", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("operations", "broker_report_id")
    op.drop_column("operations", "code")
    op.drop_column("investment_account", "broker_name")
    op.drop_index(op.f("ix_operation_securities_id"), table_name="operation_securities")
    op.drop_table("operation_securities")
    op.drop_index(op.f("ix_broker_report_id"), table_name="broker_report")
    op.drop_table("broker_report")
    op.drop_index(op.f("ix_assets_id"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
